# Generated by Django 4.0 on 2021-12-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Member',
        ),
    ]
