# Generated by Django 4.0 on 2021-12-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.CharField(choices=[('StepTech', 'StepTech'), ('StepMark', 'StepMark'), ('StepPro', 'StepPro'), ('StepCon', 'StepCon'), ('StepMan', 'StepMan')], default='StepTech', max_length=200),
        ),
    ]
